spring:
  application:
    name: hospitalManagement
  datasource:
    url: jdbc:postgresql://localhost:5432/hospitalDB
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    # database-platform: org.hibernate.dialect.PostgreSQLDialect  # Tells Hibernate which SQL dialect to use
    properties:
      hibernate:
        format_sql: true  # Printed SQL queries nicely formatted
  security:
    user:  #default username and password
      name: user
      password: password
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          github:
            client-id: xxx
            client-secret: xxx
jwt:
  secretKey: "salkjlasdfjlaskjflaskjdflasdjflasdjflasdfjlasaksfjlaksjdflkasjfdlksjfdlkjalkfsjdfjlaskfjaslkfjlasfjaskdfjasldfjlknvoiwjjlkajsf"
#  expiration: 3600000   # 1 hour in ms


#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui.html